### ISSUE TITLE
Cannot access desktop and polybar tray broken

### ISSUE THREAD

**Issue by bhcopeland** [csxr/i3-gnome#27] opened 2018-07-24 20:40 UTC
Hi,

Just started using this and find it much better thanks for the work.

- When I try and access my desktop, I can select the workspace number but it just shows the previous workspace until I launch something over the top of it. I cannot get the wallpaper/desktop to show.
- i3status shows the tray but polybar does not. The tray is launched but all the icons are messed up and broken.

**Comment by ctrs** [comment] 2018-07-25 02:05
Hi,

That's definitely a weird behavior, but let's make sure these things:

- which version of GNOME are you running?
- consider install `gnome-flashback` (you can see why through #11 )
 
Anyway i'll figure out what's going on, this is the first time this behavior is mentioned.

**Comment by yankcrime** [comment] 2018-08-22 14:04
I've found that the problem with the desktop image persistence goes away if you use a tool like [feh](https://wiki.archlinux.org/index.php/feh) to set a background _after_ i3 has started.

**Comment by makkanx** [comment] 2019-03-07 08:54
I'm using i3 and polybar and don't see any icons. Can I help in troubleshooting this somehow?

**Comment by csxr** [comment] 2019-03-18 07:32
@makkanx did the icons appear outside i3-gnome?

**Comment by makkanx** [comment] 2019-03-18 07:39
Using i3 only they appear.

**Comment by csxr** [comment] 2019-03-18 07:45
ok, there are error logs or something?
I don't use polybar, but you can look into:
- https://github.com/jaagr/polybar/issues/723
- https://github.com/jaagr/polybar/issues/1355

Hope it helps.

**Comment by makkanx** [comment] 2019-03-18 07:58
After adding wm-restack = i3 two icons appeared but not all others. Usually I have like 5-6 icons showing.

**Comment by makkanx** [comment] 2019-03-18 09:26
Here are the icons I see when I have only i3.
![Selection_903](https://user-images.githubusercontent.com/23656539/54520112-366c3b80-4968-11e9-98a5-d29267427eb1.jpg)
When I use i3-gnome I see only pidgin and nm-applet.

**Comment by over80** [comment] 2019-03-23 03:45
I have probably same problem, but I found a solution.
Missing icons (They are well-integrated to GNOME indicator) are owned by `indicator-application-service` .
To confirm, just kill it: 

```sh
$ killall -r ".*indicator-application-service"
```

`indicator-application-service` is started by `/etc/xdg/autostart/indicator-application.desktop`.
It can be disabled to overwrite by user configuration like below:

```sh
$ mkdir -p ~/.config/autostart
$ cp /etc/xdg/autostart/indicator-application.desktop ~/.config/autostart/
$ vim ~/.config/autostart/indicator-application.desktop   # edit AutostartCondition like below:
```

```
AutostartCondition=GNOME3 unless-session i3-gnome
```

It works for me. 

(I think it is good to disable other applications which have `AutostartCondition=GNOME3 unless-session gnome` too.)

**Comment by csxr** [comment] 2019-03-25 03:56
@over80 you're approach is really useful and I think the reason this happens is because as you mention:

> ...(They are well-integrated to GNOME indicator) are owned by indicator-application-service .

So it's kind of conflictive for the indicators where show in having started the session under i3 + GNOME.

Haven't received (yet) the anwser from @makkanx to confirm that yor approach worked for his issue but I'll add to the wiki as a documentation.

Thanks!

**Comment by makkanx** [comment] 2019-03-25 06:57
Confirmed, this fixes it. Now I just need to get rid of nautilus also.

**Comment by csxr** [comment] 2019-03-25 07:07
Ok, got it. This issue is fixed. Closing.

**Closed** 2019-03-25 07:07 UTC
Labels: question

**Comment by radubacaran** [comment] 2019-04-28 22:02
I can confirm @over80 solution worked for me.

**Comment by libre-man** [comment] 2020-08-11 13:50
The fix doesn't work for me unfortunately, there doesn't seem to be any process named `indicator-application-service`, and the tray is not really visible (only a few icons, but not slack for example). This is with `gnome-flashback 3.36.3`.

**Comment by jcstr** [comment] 2020-08-11 19:52
@muktupavels I think you might have the answer for this.

**Comment by muktupavels** [comment] 2020-08-11 19:57
@libre-man Is `status-notifier-watcher` disabled? `gsettings get org.gnome.gnome-flashback status-notifier-watcher`

**Comment by libre-man** [comment] 2020-08-11 21:46
Thanks @muktupavels disabling that seems to solve it. Thanks so much :)
